
platform:ios,'8.0'

inhibit_all_warnings!

use_frameworks!

#source 'https://git.coding.net/hging/Specs.git'

pre_install do
    system("sed -i '' '/UITextField/d' Pods/BlocksKit/BlocksKit/BlocksKit+UIKit.h")
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.h')
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.m')
end

target ‘KMDance’ do
 
    pod 'Reachability', '3.2'
    pod 'SVProgressHUD', '2.0.3'
    pod 'AFNetworking', '3.1.0'
    pod 'SDWebImage', '4.2.2'
    pod 'Masonry', '1.1.0'
    pod 'FMDB', '2.6.2'
    pod 'MJRefresh', '3.1.12'
    pod 'Base64', '1.1.2'
    pod 'SFHFKeychainUtils', '0.0.1'
    pod 'SDCycleScrollView', '1.74'
    pod 'MJExtension', '3.0.13'
    pod 'BlocksKit', '2.2.5'
    pod 'CocoaLumberjack', '2.2.0'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'AspectsV1.4.2', '1.4.2'
    pod 'TZImagePickerController', '1.9.4'
    pod 'WZLBadge', '1.2.5'
    pod 'CYLTabBarController', '1.14.1'
    pod 'MLeaksFinder', '0.2.1'
    pod 'WHC_KeyboardManager_oc', '1.0.9'
    #    pod 'MZTimerLabel', '0.5.4'
    pod 'YYText', '1.0.7'
    pod 'STPickerView', '1.0.0'
    pod 'DZNEmptyDataSet', '1.8.1'
    pod 'StreamingKit', '0.1.29'
    pod 'ZLPhotoBrowser', '2.5.2'

end
